// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF6KVNxEdNAs1utGTwR0fyfHp5F2Ezir8',
    appId: '1:54456157133:web:31ee201a5b1ea6c9f77a84',
    messagingSenderId: '54456157133',
    projectId: 'sneakerhead-4a4ba',
    authDomain: 'sneakerhead-4a4ba.firebaseapp.com',
    storageBucket: 'sneakerhead-4a4ba.firebasestorage.app',
    measurementId: 'G-JSBY5DT2R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkCzypN9I6L8AllyKSERlxRk5HExq7d8',
    appId: '1:54456157133:android:2053557ac977c346f77a84',
    messagingSenderId: '54456157133',
    projectId: 'sneakerhead-4a4ba',
    storageBucket: 'sneakerhead-4a4ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4qGgHsWeAV7zyk6UyYP21v9mOePoZjxA',
    appId: '1:54456157133:ios:9b571affcf2f4e9bf77a84',
    messagingSenderId: '54456157133',
    projectId: 'sneakerhead-4a4ba',
    storageBucket: 'sneakerhead-4a4ba.firebasestorage.app',
    androidClientId: '54456157133-oftnsoim7g1703584ofj1mn20u5tfm42.apps.googleusercontent.com',
    iosClientId: '54456157133-m3jepmbukegefebl2f52jfgb5927qleo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakerhead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4qGgHsWeAV7zyk6UyYP21v9mOePoZjxA',
    appId: '1:54456157133:ios:9b571affcf2f4e9bf77a84',
    messagingSenderId: '54456157133',
    projectId: 'sneakerhead-4a4ba',
    storageBucket: 'sneakerhead-4a4ba.firebasestorage.app',
    androidClientId: '54456157133-oftnsoim7g1703584ofj1mn20u5tfm42.apps.googleusercontent.com',
    iosClientId: '54456157133-m3jepmbukegefebl2f52jfgb5927qleo.apps.googleusercontent.com',
    iosBundleId: 'com.example.sneakerhead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF6KVNxEdNAs1utGTwR0fyfHp5F2Ezir8',
    appId: '1:54456157133:web:f19eb5bc6328fd04f77a84',
    messagingSenderId: '54456157133',
    projectId: 'sneakerhead-4a4ba',
    authDomain: 'sneakerhead-4a4ba.firebaseapp.com',
    storageBucket: 'sneakerhead-4a4ba.firebasestorage.app',
    measurementId: 'G-Q0V1PWQ67K',
  );

}