// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl5YFk9snLETKYDL2WeXtV-zO4SkbmgVo',
    appId: '1:617356778535:web:2dd9c779ba651070380202',
    messagingSenderId: '617356778535',
    projectId: 'sneakerhead-5a996',
    authDomain: 'sneakerhead-5a996.firebaseapp.com',
    storageBucket: 'sneakerhead-5a996.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7a2IirVeWvmOeYSamT7WTHtGtQ4cQcNs',
    appId: '1:617356778535:android:d51c54c97cd3db15380202',
    messagingSenderId: '617356778535',
    projectId: 'sneakerhead-5a996',
    storageBucket: 'sneakerhead-5a996.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNkhv1YBP6oUSkDBC7rH6xjq314l7CGl0',
    appId: '1:617356778535:ios:10fa2945c520905b380202',
    messagingSenderId: '617356778535',
    projectId: 'sneakerhead-5a996',
    storageBucket: 'sneakerhead-5a996.firebasestorage.app',
    iosBundleId: 'com.example.sneakerhead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNkhv1YBP6oUSkDBC7rH6xjq314l7CGl0',
    appId: '1:617356778535:ios:1e4d9e34d4570aac380202',
    messagingSenderId: '617356778535',
    projectId: 'sneakerhead-5a996',
    storageBucket: 'sneakerhead-5a996.firebasestorage.app',
    iosBundleId: 'com.example.sneakerhead.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl5YFk9snLETKYDL2WeXtV-zO4SkbmgVo',
    appId: '1:617356778535:web:41a5524c874e082e380202',
    messagingSenderId: '617356778535',
    projectId: 'sneakerhead-5a996',
    authDomain: 'sneakerhead-5a996.firebaseapp.com',
    storageBucket: 'sneakerhead-5a996.firebasestorage.app',
  );
}
